EANs may strip leading zeros
kaize/validates pull request #51
Opened 2016-11-18 14:33 UTC by Bahanix

Our warehouses have loads of 11 and 12 digits EANs: in order to save space on small products packaging, companies strip leading 0 from their EANs.

2016-12-21 14:41 UTC, Bahanix commented
:up: :)

2016-12-21 15:20 UTC, zzet requested changes

2016-12-21 15:20 UTC, zzet commented on lib/ean_validator.rb
> +    ean.rjust(13, "0".freeze).split(//).each_with_index.inject(0){ |s, (v, i)| s + v.to_i * EAN_CHECK_DIGIT13[i] } % 10 == 0
I think we can make some optimization in this PR:

```ruby
ean.rjust(13, "0".freeze).split(//).each_with_index.inject(0){ |s, (v, i)| s + v.to_i * EAN_CHECK_DIGIT13[i] } % 10 == 0
```
vs
```ruby
ean.rjust(13, "0".freeze).each_char.map.with_index { |ch, i| ch.to_i * EAN_CHECK_DIGIT13[i] }.reduce(:+) % 10 == 0
```

```ruby
Benchmark.bm do |x| 
  x.report do
    n.times do
      ean.rjust(13, "0".freeze).split(//).each_with_index.inject(0){ |s, (v, i)| s + v.to_i * EAN_CHECK_DIGIT13[i] } % 10 == 0
    end
  end
  x.report do
    n.times do
      ean.rjust(13, "0".freeze).each_char.map.with_index { |ch, i| ch.to_i * EAN_CHECK_DIGIT13[i] }.reduce(:+) % 10 == 0
    end
  end
end
```

```
       user     system      total        real
   0.550000   0.000000   0.550000 (  0.554524)
   0.300000   0.000000   0.300000 (  0.294683)
```

2017-01-13 10:57 UTC, Bahanix commented
@zzet updated, thanks for your feedbacks

2017-01-13 11:02 UTC, zzet approved these changes

2017-01-13 11:02 UTC, merged